/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include "opencv2/opencv.hpp"
/* Header for class com_kmitl_powfeez_OpencvClass */

using namespace cv;
using namespace std;
#ifndef _Included_com_kmitl_powfeez_OpencvClass
#define _Included_com_kmitl_powfeez_OpencvClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kmitl_powfeez_OpencvClass
 * Method:    Obj1Detection
 * Signature: (J)V
 */

void detect(Mat& frame);
JNIEXPORT void JNICALL Java_com_kmitl_powfeez_OpencvClass_Obj1Detection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
